### ISSUE TITLE
tensor sizes don't match

### ISSUE THREAD

**Issue by Nighteye** [JannerM/intrinsics-network#2]
Hi!
Thank you for the hard work
I'm trying to run the decomposer, but I somehow get the runtime error "normed = normals / (magnitude + 1e-6)", one tensor is of size 3 and the other 60, in the models/primitives.py file.
Wouldn't it be better to permute the dimension before:
"magnitude = magnitude.repeat(3,1,1,1).permute(1, 0, 2, 3)"
I use python 3.6 from anaconda and pytorch 0.3.0

**Comment by Nighteye** [comment]
I guess the same fix should be applied to line 58 of file pipeline/utils.py:
`        mask = mask.repeat(3,1,1,1).permute(1, 0, 2, 3)
`

**Comment by jannerm** [comment]
I bet this is a PyTorch version problem. There were a few breaking changes introduced in 0.2.0, detailed [here](https://github.com/pytorch/pytorch/releases/tag/v0.2.0). (I was using 0.1.12 when I wrote this code.) If you change [this line](https://github.com/JannerM/intrinsics-network/blob/master/models/primitives.py#L39) to: 
`magnitude = torch.pow(normals, 2).sum(1, keepdim=True)`, it should fix the issue. 

I tested this out in PyTorch 0.3.0, but haven't pushed the change yet because it would break compatibility with 0.1.12. Given the other issues you found, it seems that there are a few more subtle problems to deal with before moving this repo to 0.3.0. Thanks for reporting them!

**Comment by jannerm** [comment]
By the way, it also makes sense that this error cropped up in pipeline/utils.py, as there were other summations there. Adding the `keepdim=True` flag [here](https://github.com/JannerM/intrinsics-network/blob/master/pipeline/utils.py#L55) and [here](https://github.com/JannerM/intrinsics-network/blob/master/pipeline/utils.py#L58) should help as well.

**Comment by Nighteye** [comment]
Thank you for the prompt response! 
It solves the problem, however I will keep using PyTorch 0.1.12 due to other issues mentioned in [https://github.com/JannerM/intrinsics-network/issues/4](url)
